image: docker:stable

services:
  - docker:18.09-dind

stages:
  - build
  - dockerize
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE
  CONTAINER_NAME: frontend

build:
  image: node:12.4.0
  stage: build
  script:
    - ./run_build.sh
  artifacts:
    paths:
      - build

dockerize:
  before_script:
    - docker info
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  stage: dockerize
  script:
    - docker build --tag $IMAGE_TAG .
    - docker push $IMAGE_TAG

trigger_build:
  stage: deploy
  script:
    - "curl -X POST -F token=TOKEN -F ref=REF_NAME https://gitlab.com/api/v4/projects/13753673/trigger/pipeline"
