image: docker:stable

services:
  - docker:18.09-dind

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build
  - dockerize

variables:
  IMAGE_TAG: -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  CONTAINER_NAME: frontend
  DOCKER_HOST: tcp://docker:2375

build:
  stage: build
  script:
    - docker run
      --mount type=bind,source="$(pwd)",target=/app
      node:12.4.0
      /bin/bash -c /app/run_build.sh
  artifacts:
    paths:
      - build

dockerize:
  stage: dockerize
  script:
    - docker build --tag $IMAGE_TAG .
    - docker push $IMAGE_TAG
