image: docker:latest

services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
    DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - dockerize

variables:
  IMAGE_TAG: -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  CONTAINER_NAME: frontend

before_script:
  - docker info
build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker run
      --mount type=bind,source="$(pwd)",target=/app
      node:12.4.0
      /bin/bash -c /app/run_build.sh
  artifacts:
    paths:
      - build

dockerize:
  stage: dockerize
  script:
    - docker login $CI_REGISTRY
    - docker build --tag $IMAGE_TAG .
    - docker push $IMAGE_TAG
